# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fuzzer

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]
       
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install atheris
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: khushi2/oss-fuzz
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
  
  Fuzzing:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            sanitizer: [address]
    steps:
    - uses: actions/checkout@v3
    - name: Build Fuzzers (${{ matrix.sanitizer }})
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        language: python
        dry-run: false
        sanitizer: ${{ matrix.sanitizer }}
        
    - name: Scan Report
      uses: actions/upload-artifact@v2
      with:
          name: scan-report
          path: 'report.html'    
        
    - name: Run Fuzzers (${{ matrix.sanitizer }})
      uses: google/clusterfuzzlite/actions/run_fuzzers@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        language: python
        fuzz-seconds: 120
        mode: 'batch'
        dry-run: false
        sanitizer: ${{ matrix.sanitizer }}
        storage-repo: https://${{ secrets.TOKEN }}@github.com/Clusterfuzzlite.git
        storage-repo-branch: master
      
  
  Pruning:
    runs-on: ubuntu-latest
    steps:
    
    - name: Build Fuzzers
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@v1
      with:
        language: python
        upload-build: true
      
        

    - name: Run Fuzzers
      id: run
      uses: google/clusterfuzzlite/actions/run_fuzzers@v1
      with:
        language: python
        github-token: ${{ secrets.TOKEN }}
        fuzz-seconds: 120
        mode: 'prune'
        storage-repo: https://${{ secrets.TOKEN }}@github.com/Clusterfuzzlite.git
        storage-repo-branch: master
      
  

 
  Coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@v1
      with:
        sanitizer: coverage
        language: python
    - name: Run Fuzzers
      id: run
      uses: google/clusterfuzzlite/actions/run_fuzzers@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: 600
        language: python
        mode: 'coverage'
        sanitizer: 'coverage'
        storage-repo: https://${{ secrets.TOKEN }}@github.com/Clusterfuzzlite.git
        storage-repo-branch: master
      
        
